package com.eraisedtox94.smartdiary.emoticon;

/**
 * Created by spraful on 09-Jun-17.
 */

public class Daily {

    public static MyEmojicon[] getData(){
        MyEmojicon []DATA  = {
                new MyEmojicon(getEmojiByUnicode(0x2709)),
                new MyEmojicon(getEmojiByUnicode(0x1F6AC)),
                new MyEmojicon(getEmojiByUnicode(0x1F6AD)),
                new MyEmojicon(getEmojiByUnicode(0x1F6BD)),
                new MyEmojicon(getEmojiByUnicode(0x1F6BE)),
                new MyEmojicon(getEmojiByUnicode(0x1F6C0)),
                new MyEmojicon(getEmojiByUnicode(0x231A)),
                new MyEmojicon(getEmojiByUnicode(0x231B)),
                new MyEmojicon(getEmojiByUnicode(0x23F0)),
                new MyEmojicon(getEmojiByUnicode(0x260E)),
                new MyEmojicon(getEmojiByUnicode(0x26FD)),
                new MyEmojicon(getEmojiByUnicode(0x1F380)),
                new MyEmojicon(getEmojiByUnicode(0x1F381)),
                new MyEmojicon(getEmojiByUnicode(0x1F382)),
                new MyEmojicon(getEmojiByUnicode(0x1F383)),
                new MyEmojicon(getEmojiByUnicode(0x1F384)),
                new MyEmojicon(getEmojiByUnicode(0x1F385)),
                new MyEmojicon(getEmojiByUnicode(0x1F388)),
                new MyEmojicon(getEmojiByUnicode(0x1F389)),
                new MyEmojicon(getEmojiByUnicode(0x1F38F)),
                new MyEmojicon(getEmojiByUnicode(0x1F390)),
                new MyEmojicon(getEmojiByUnicode(0x1F391)),
                new MyEmojicon(getEmojiByUnicode(0x1F392)),
                new MyEmojicon(getEmojiByUnicode(0x1F393)),
                new MyEmojicon(getEmojiByUnicode(0x1F3A0)),
                new MyEmojicon(getEmojiByUnicode(0x1F3A1)),
                new MyEmojicon(getEmojiByUnicode(0x1F3A2)),
                new MyEmojicon(getEmojiByUnicode(0x1F3A3)),
                new MyEmojicon(getEmojiByUnicode(0x1F3A4)),
                new MyEmojicon(getEmojiByUnicode(0x1F3A5)),
                new MyEmojicon(getEmojiByUnicode(0x1F3A6)),
                new MyEmojicon(getEmojiByUnicode(0x1F3A7)),
                new MyEmojicon(getEmojiByUnicode(0x1F3A8)),
                new MyEmojicon(getEmojiByUnicode(0x1F3A9)),
                new MyEmojicon(getEmojiByUnicode(0x1F3AA)),
                new MyEmojicon(getEmojiByUnicode(0x1F3AB)),
                new MyEmojicon(getEmojiByUnicode(0x1F3AC)),
                new MyEmojicon(getEmojiByUnicode(0x1F3AD)),
                new MyEmojicon(getEmojiByUnicode(0x1F3AE)),
                new MyEmojicon(getEmojiByUnicode(0x1F3AF)),
                new MyEmojicon(getEmojiByUnicode(0x1F4A1)),
                new MyEmojicon(getEmojiByUnicode(0x1F4A3)),
                new MyEmojicon(getEmojiByUnicode(0x1F4A4)),
                new MyEmojicon(getEmojiByUnicode(0x1F4B0)),
                new MyEmojicon(getEmojiByUnicode(0x1F4B2)),
                new MyEmojicon(getEmojiByUnicode(0x1F4B3)),
                new MyEmojicon(getEmojiByUnicode(0x1F4B4)),
                new MyEmojicon(getEmojiByUnicode(0x1F4B5)),
                new MyEmojicon(getEmojiByUnicode(0x1F4B8)),
                new MyEmojicon(getEmojiByUnicode(0x1F4BA)),
                new MyEmojicon(getEmojiByUnicode(0x1F4BB)),
                new MyEmojicon(getEmojiByUnicode(0x1F4BC)),
                new MyEmojicon(getEmojiByUnicode(0x1F4BD)),
                new MyEmojicon(getEmojiByUnicode(0x1F4BE)),
                new MyEmojicon(getEmojiByUnicode(0x1F4BF)),
                new MyEmojicon(getEmojiByUnicode(0x1F4C0)),
                new MyEmojicon(getEmojiByUnicode(0x1F4C1)),
                new MyEmojicon(getEmojiByUnicode(0x1F4C2)),
                new MyEmojicon(getEmojiByUnicode(0x1F4C3)),
                new MyEmojicon(getEmojiByUnicode(0x1F4C4)),
                new MyEmojicon(getEmojiByUnicode(0x1F4C5)),
                new MyEmojicon(getEmojiByUnicode(0x1F4C6)),
                new MyEmojicon(getEmojiByUnicode(0x1F4C7)),
                new MyEmojicon(getEmojiByUnicode(0x1F4C8)),
                new MyEmojicon(getEmojiByUnicode(0x1F4C9)),
                new MyEmojicon(getEmojiByUnicode(0x1F4CA)),
                new MyEmojicon(getEmojiByUnicode(0x1F4CB)),
                new MyEmojicon(getEmojiByUnicode(0x1F4CC)),
                new MyEmojicon(getEmojiByUnicode(0x1F4CD)),
                new MyEmojicon(getEmojiByUnicode(0x1F4CE)),
                new MyEmojicon(getEmojiByUnicode(0x1F4CF)),
                new MyEmojicon(getEmojiByUnicode(0x1F4D0)),
                new MyEmojicon(getEmojiByUnicode(0x1F4D1)),
                new MyEmojicon(getEmojiByUnicode(0x1F4D2)),
                new MyEmojicon(getEmojiByUnicode(0x1F4D3)),
                new MyEmojicon(getEmojiByUnicode(0x1F4D4)),
                new MyEmojicon(getEmojiByUnicode(0x1F4D5)),
                new MyEmojicon(getEmojiByUnicode(0x1F4D6)),
                new MyEmojicon(getEmojiByUnicode(0x1F4D7)),
                new MyEmojicon(getEmojiByUnicode(0x1F4D8)),
                new MyEmojicon(getEmojiByUnicode(0x1F4D9)),
                new MyEmojicon(getEmojiByUnicode(0x1F4DA)),
                new MyEmojicon(getEmojiByUnicode(0x1F4DB)),
                new MyEmojicon(getEmojiByUnicode(0x1F4DC)),
                new MyEmojicon(getEmojiByUnicode(0x1F4DD)),
                new MyEmojicon(getEmojiByUnicode(0x1F4DE)),
                new MyEmojicon(getEmojiByUnicode(0x1F4DF)),
                new MyEmojicon(getEmojiByUnicode(0x1F4E0)),
                new MyEmojicon(getEmojiByUnicode(0x1F4E1)),
                new MyEmojicon(getEmojiByUnicode(0x1F4E2)),
                new MyEmojicon(getEmojiByUnicode(0x1F4E3)),
                new MyEmojicon(getEmojiByUnicode(0x1F4E4)),
                new MyEmojicon(getEmojiByUnicode(0x1F4E5)),
                new MyEmojicon(getEmojiByUnicode(0x1F4E6)),
                new MyEmojicon(getEmojiByUnicode(0x1F4E7)),
                new MyEmojicon(getEmojiByUnicode(0x1F4E8)),
                new MyEmojicon(getEmojiByUnicode(0x1F4E9)),
                new MyEmojicon(getEmojiByUnicode(0x1F4EA)),
                new MyEmojicon(getEmojiByUnicode(0x1F4EB)),
                new MyEmojicon(getEmojiByUnicode(0x1F4EE)),
                new MyEmojicon(getEmojiByUnicode(0x1F4F0)),
                new MyEmojicon(getEmojiByUnicode(0x1F4F1)),
                new MyEmojicon(getEmojiByUnicode(0x1F4F2)),
                new MyEmojicon(getEmojiByUnicode(0x1F4F3)),
                new MyEmojicon(getEmojiByUnicode(0x1F4F4)),
                new MyEmojicon(getEmojiByUnicode(0x1F4F6)),
                new MyEmojicon(getEmojiByUnicode(0x1F4F7)),
                new MyEmojicon(getEmojiByUnicode(0x1F4F9)),
                new MyEmojicon(getEmojiByUnicode(0x1F4FA)),
                new MyEmojicon(getEmojiByUnicode(0x1F4FB)),
                new MyEmojicon(getEmojiByUnicode(0x1F4FC)),
                new MyEmojicon(getEmojiByUnicode(0x1F503)),
                new MyEmojicon(getEmojiByUnicode(0x1F50A)),
                new MyEmojicon(getEmojiByUnicode(0x1F50B)),
                new MyEmojicon(getEmojiByUnicode(0x1F50C)),
                new MyEmojicon(getEmojiByUnicode(0x1F50D)),
                new MyEmojicon(getEmojiByUnicode(0x1F50E)),
                new MyEmojicon(getEmojiByUnicode(0x1F50F)),
                new MyEmojicon(getEmojiByUnicode(0x1F511)),
                new MyEmojicon(getEmojiByUnicode(0x1F512)),
                new MyEmojicon(getEmojiByUnicode(0x1F513)),
                new MyEmojicon(getEmojiByUnicode(0x1F514)),
                new MyEmojicon(getEmojiByUnicode(0x1F515)),
                new MyEmojicon(getEmojiByUnicode(0x1F516)),
                new MyEmojicon(getEmojiByUnicode(0x1F517)),
                new MyEmojicon(getEmojiByUnicode(0x1F525)),
                new MyEmojicon(getEmojiByUnicode(0x1F526)),
                new MyEmojicon(getEmojiByUnicode(0x1F527)),
                new MyEmojicon(getEmojiByUnicode(0x1F528)),
                new MyEmojicon(getEmojiByUnicode(0x1F529)),
                new MyEmojicon(getEmojiByUnicode(0x1F52A)),
                new MyEmojicon(getEmojiByUnicode(0x1F52B)),
                new MyEmojicon(getEmojiByUnicode(0x1F52E)),
                new MyEmojicon(getEmojiByUnicode(0x1F6BF)),
                new MyEmojicon(getEmojiByUnicode(0x1F6C1)),
                new MyEmojicon(getEmojiByUnicode(0x1F4B6)),
                new MyEmojicon(getEmojiByUnicode(0x1F4B7)),
                new MyEmojicon(getEmojiByUnicode(0x1F4EC)),
                new MyEmojicon(getEmojiByUnicode(0x1F4ED)),
                new MyEmojicon(getEmojiByUnicode(0x1F4EE)),
                new MyEmojicon(getEmojiByUnicode(0x1F4F5)),
                new MyEmojicon(getEmojiByUnicode(0x1F507)),
                new MyEmojicon(getEmojiByUnicode(0x1F509)),
                new MyEmojicon(getEmojiByUnicode(0x1F515)),
                new MyEmojicon(getEmojiByUnicode(0x1F52C)),
                new MyEmojicon(getEmojiByUnicode(0x1F52D)),
        };


        return DATA;
    }

    public static String getEmojiByUnicode(int unicode){
        return new String(Character.toChars(unicode));
    }
}
