package com.eraisedtox94.smartdiary.emoticon;


/**
 * @author spraful
 */
public class Nature {

    public static MyEmojicon[] getData() {
        MyEmojicon[] DATA = {
                new MyEmojicon(getEmojiByUnicode(0x2744)),
                new MyEmojicon(getEmojiByUnicode(0x2600)),
                new MyEmojicon(getEmojiByUnicode(0x2601)),
                new MyEmojicon(getEmojiByUnicode(0x2614)),
                new MyEmojicon(getEmojiByUnicode(0x26C4)),
                new MyEmojicon(getEmojiByUnicode(0x26C5)),
                new MyEmojicon(getEmojiByUnicode(0x1F300)),
                new MyEmojicon(getEmojiByUnicode(0x1F302)),
                new MyEmojicon(getEmojiByUnicode(0x1F304)),
                new MyEmojicon(getEmojiByUnicode(0x1F305)),
                new MyEmojicon(getEmojiByUnicode(0x1F308)),
                new MyEmojicon(getEmojiByUnicode(0x1F30C)),
                new MyEmojicon(getEmojiByUnicode(0x1F30F)),
                new MyEmojicon(getEmojiByUnicode(0x1F311)),
                new MyEmojicon(getEmojiByUnicode(0x1F313)),
                new MyEmojicon(getEmojiByUnicode(0x1F314)),
                new MyEmojicon(getEmojiByUnicode(0x1F315)),
                new MyEmojicon(getEmojiByUnicode(0x1F319)),
                new MyEmojicon(getEmojiByUnicode(0x1F31B)),
                new MyEmojicon(getEmojiByUnicode(0x1F31F)),
                new MyEmojicon(getEmojiByUnicode(0x1F320)),
                new MyEmojicon(getEmojiByUnicode(0x1F334)),
                new MyEmojicon(getEmojiByUnicode(0x1F335)),
                new MyEmojicon(getEmojiByUnicode(0x1F337)),
                new MyEmojicon(getEmojiByUnicode(0x1F338)),
                new MyEmojicon(getEmojiByUnicode(0x1F339)),
                new MyEmojicon(getEmojiByUnicode(0x1F33A)),
                new MyEmojicon(getEmojiByUnicode(0x1F33B)),
                new MyEmojicon(getEmojiByUnicode(0x1F33C)),
                new MyEmojicon(getEmojiByUnicode(0x1F33D)),
                new MyEmojicon(getEmojiByUnicode(0x1F33E)),
                new MyEmojicon(getEmojiByUnicode(0x1F33F)),
                new MyEmojicon(getEmojiByUnicode(0x1F340)),
                new MyEmojicon(getEmojiByUnicode(0x1F341)),
                new MyEmojicon(getEmojiByUnicode(0x1F342)),
                new MyEmojicon(getEmojiByUnicode(0x1F343)),
                new MyEmojicon(getEmojiByUnicode(0x1F344)),
                new MyEmojicon(getEmojiByUnicode(0x1F40C)),
                new MyEmojicon(getEmojiByUnicode(0x1F40D)),
                new MyEmojicon(getEmojiByUnicode(0x1F40E)),
                new MyEmojicon(getEmojiByUnicode(0x1F411)),
                new MyEmojicon(getEmojiByUnicode(0x1F412)),
                new MyEmojicon(getEmojiByUnicode(0x1F414)),
                new MyEmojicon(getEmojiByUnicode(0x1F417)),
                new MyEmojicon(getEmojiByUnicode(0x1F418)),
                new MyEmojicon(getEmojiByUnicode(0x1F419)),
                new MyEmojicon(getEmojiByUnicode(0x1F41A)),
                new MyEmojicon(getEmojiByUnicode(0x1F41B)),
                new MyEmojicon(getEmojiByUnicode(0x1F41C)),
                new MyEmojicon(getEmojiByUnicode(0x1F41D)),
                new MyEmojicon(getEmojiByUnicode(0x1F41E)),
                new MyEmojicon(getEmojiByUnicode(0x1F41F)),
                new MyEmojicon(getEmojiByUnicode(0x1F420)),
                new MyEmojicon(getEmojiByUnicode(0x1F421)),
                new MyEmojicon(getEmojiByUnicode(0x1F422)),
                new MyEmojicon(getEmojiByUnicode(0x1F423)),
                new MyEmojicon(getEmojiByUnicode(0x1F424)),
                new MyEmojicon(getEmojiByUnicode(0x1F425)),
                new MyEmojicon(getEmojiByUnicode(0x1F426)),
                new MyEmojicon(getEmojiByUnicode(0x1F427)),
                new MyEmojicon(getEmojiByUnicode(0x1F428)),
                new MyEmojicon(getEmojiByUnicode(0x1F429)),
                new MyEmojicon(getEmojiByUnicode(0x1F42B)),
                new MyEmojicon(getEmojiByUnicode(0x1F42C)),
                new MyEmojicon(getEmojiByUnicode(0x1F42D)),
                new MyEmojicon(getEmojiByUnicode(0x1F42E)),
                new MyEmojicon(getEmojiByUnicode(0x1F42F)),
                new MyEmojicon(getEmojiByUnicode(0x1F430)),
                new MyEmojicon(getEmojiByUnicode(0x1F431)),
                new MyEmojicon(getEmojiByUnicode(0x1F432)),
                new MyEmojicon(getEmojiByUnicode(0x1F433)),
                new MyEmojicon(getEmojiByUnicode(0x1F434)),
                new MyEmojicon(getEmojiByUnicode(0x1F435)),
                new MyEmojicon(getEmojiByUnicode(0x1F436)),
                new MyEmojicon(getEmojiByUnicode(0x1F437)),
                new MyEmojicon(getEmojiByUnicode(0x1F438)),
                new MyEmojicon(getEmojiByUnicode(0x1F439)),
                new MyEmojicon(getEmojiByUnicode(0x1F43A)),
                new MyEmojicon(getEmojiByUnicode(0x1F43B)),
                new MyEmojicon(getEmojiByUnicode(0x1F43C)),
                new MyEmojicon(getEmojiByUnicode(0x1F43D)),
                new MyEmojicon(getEmojiByUnicode(0x1F43E)),
                new MyEmojicon(getEmojiByUnicode(0x1F4A0)),
                new MyEmojicon(getEmojiByUnicode(0x1F4A7)),
                new MyEmojicon(getEmojiByUnicode(0x1F4AE)),
                new MyEmojicon(getEmojiByUnicode(0x1F30D)),
                new MyEmojicon(getEmojiByUnicode(0x1F30E)),
                new MyEmojicon(getEmojiByUnicode(0x1F310)),
                new MyEmojicon(getEmojiByUnicode(0x1F312)),
                new MyEmojicon(getEmojiByUnicode(0x1F316)),
                new MyEmojicon(getEmojiByUnicode(0x1F317)),
                new MyEmojicon(getEmojiByUnicode(0x1F318)),
                new MyEmojicon(getEmojiByUnicode(0x1F31A)),
                new MyEmojicon(getEmojiByUnicode(0x1F31C)),
                new MyEmojicon(getEmojiByUnicode(0x1F31D)),
                new MyEmojicon(getEmojiByUnicode(0x1F31E)),
                new MyEmojicon(getEmojiByUnicode(0x1F332)),
                new MyEmojicon(getEmojiByUnicode(0x1F333)),
                new MyEmojicon(getEmojiByUnicode(0x1F400)),
                new MyEmojicon(getEmojiByUnicode(0x1F401)),
                new MyEmojicon(getEmojiByUnicode(0x1F402)),
                new MyEmojicon(getEmojiByUnicode(0x1F403)),
                new MyEmojicon(getEmojiByUnicode(0x1F404)),
                new MyEmojicon(getEmojiByUnicode(0x1F405)),
                new MyEmojicon(getEmojiByUnicode(0x1F406)),
                new MyEmojicon(getEmojiByUnicode(0x1F407)),
                new MyEmojicon(getEmojiByUnicode(0x1F408)),
                new MyEmojicon(getEmojiByUnicode(0x1F409)),
                new MyEmojicon(getEmojiByUnicode(0x1F40A)),
                new MyEmojicon(getEmojiByUnicode(0x1F40B)),
                new MyEmojicon(getEmojiByUnicode(0x1F40F)),
                new MyEmojicon(getEmojiByUnicode(0x1F410)),
                new MyEmojicon(getEmojiByUnicode(0x1F413)),
                new MyEmojicon(getEmojiByUnicode(0x1F415)),
                new MyEmojicon(getEmojiByUnicode(0x1F416)),
                new MyEmojicon(getEmojiByUnicode(0x1F42A)),

        };
        return DATA;
    }

    public static String getEmojiByUnicode(int unicode) {
        return new String(Character.toChars(unicode));
    }

}
