package com.eraisedtox94.smartdiary.emoticon;

/**
 * @author spraful
 */
public class People {



    public static MyEmojicon[] getData(){
        MyEmojicon []DATA  = {
                new MyEmojicon(getEmojiByUnicode(0x1F601)),
                new MyEmojicon(getEmojiByUnicode(0x1F602)),
                new MyEmojicon(getEmojiByUnicode(0x1F603)),
                new MyEmojicon(getEmojiByUnicode(0x1F604)),
                new MyEmojicon(getEmojiByUnicode(0x1F605)),
                new MyEmojicon(getEmojiByUnicode(0x1F606)),
                new MyEmojicon(getEmojiByUnicode(0x1F607)),
                new MyEmojicon(getEmojiByUnicode(0x1F608)),
                new MyEmojicon(getEmojiByUnicode(0x1F609)),
                new MyEmojicon(getEmojiByUnicode(0x1F60A)),
                new MyEmojicon(getEmojiByUnicode(0x1F60B)),
                new MyEmojicon(getEmojiByUnicode(0x1F60C)),
                new MyEmojicon(getEmojiByUnicode(0x1F60D)),
                new MyEmojicon(getEmojiByUnicode(0x1F60F)),
                new MyEmojicon(getEmojiByUnicode(0x1F612)),
                new MyEmojicon(getEmojiByUnicode(0x1F613)),
                new MyEmojicon(getEmojiByUnicode(0x1F614)),
                new MyEmojicon(getEmojiByUnicode(0x1F616)),
                new MyEmojicon(getEmojiByUnicode(0x1F618)),
                new MyEmojicon(getEmojiByUnicode(0x1F61A)),
                new MyEmojicon(getEmojiByUnicode(0x1F61C)),
                new MyEmojicon(getEmojiByUnicode(0x1F61D)),
                new MyEmojicon(getEmojiByUnicode(0x1F61E)),
                new MyEmojicon(getEmojiByUnicode(0x1F620)),
                new MyEmojicon(getEmojiByUnicode(0x1F621)),
                new MyEmojicon(getEmojiByUnicode(0x1F622)),
                new MyEmojicon(getEmojiByUnicode(0x1F623)),
                new MyEmojicon(getEmojiByUnicode(0x1F624)),
                new MyEmojicon(getEmojiByUnicode(0x1F625)),
                new MyEmojicon(getEmojiByUnicode(0x1F628)),
                new MyEmojicon(getEmojiByUnicode(0x1F629)),
                new MyEmojicon(getEmojiByUnicode(0x1F62A)),
                new MyEmojicon(getEmojiByUnicode(0x1F62B)),
                new MyEmojicon(getEmojiByUnicode(0x1F62D)),
                new MyEmojicon(getEmojiByUnicode(0x1F630)),
                new MyEmojicon(getEmojiByUnicode(0x1F631)),
                new MyEmojicon(getEmojiByUnicode(0x1F632)),
                new MyEmojicon(getEmojiByUnicode(0x1F633)),
                new MyEmojicon(getEmojiByUnicode(0x1F635)),
                new MyEmojicon(getEmojiByUnicode(0x1F637)),
                new MyEmojicon(getEmojiByUnicode(0x1F638)),
                new MyEmojicon(getEmojiByUnicode(0x1F639)),
                new MyEmojicon(getEmojiByUnicode(0x1F63A)),
                new MyEmojicon(getEmojiByUnicode(0x1F63B)),
                new MyEmojicon(getEmojiByUnicode(0x1F63C)),
                new MyEmojicon(getEmojiByUnicode(0x1F63D)),
                new MyEmojicon(getEmojiByUnicode(0x1F63E)),
                new MyEmojicon(getEmojiByUnicode(0x1F63F)),
                new MyEmojicon(getEmojiByUnicode(0x1F640)),
                new MyEmojicon(getEmojiByUnicode(0x1F645)),
                new MyEmojicon(getEmojiByUnicode(0x1F646)),
                new MyEmojicon(getEmojiByUnicode(0x1F647)),
                new MyEmojicon(getEmojiByUnicode(0x1F648)),
                new MyEmojicon(getEmojiByUnicode(0x1F649)),
                new MyEmojicon(getEmojiByUnicode(0x1F64A)),
                new MyEmojicon(getEmojiByUnicode(0x1F64B)),
                new MyEmojicon(getEmojiByUnicode(0x1F64C)),
                new MyEmojicon(getEmojiByUnicode(0x1F64D)),
                new MyEmojicon(getEmojiByUnicode(0x1F64E)),
                new MyEmojicon(getEmojiByUnicode(0x1F64F)),
                new MyEmojicon(getEmojiByUnicode(0x270A)),
                new MyEmojicon(getEmojiByUnicode(0x270B)),
                new MyEmojicon(getEmojiByUnicode(0x270C)),
                new MyEmojicon(getEmojiByUnicode(0x261D)),
                new MyEmojicon(getEmojiByUnicode(0x263A)),
                new MyEmojicon(getEmojiByUnicode(0x1F440)),
                new MyEmojicon(getEmojiByUnicode(0x1F442)),
                new MyEmojicon(getEmojiByUnicode(0x1F443)),
                new MyEmojicon(getEmojiByUnicode(0x1F444)),
                new MyEmojicon(getEmojiByUnicode(0x1F445)),
                new MyEmojicon(getEmojiByUnicode(0x1F446)),
                new MyEmojicon(getEmojiByUnicode(0x1F447)),
                new MyEmojicon(getEmojiByUnicode(0x1F448)),
                new MyEmojicon(getEmojiByUnicode(0x1F449)),
                new MyEmojicon(getEmojiByUnicode(0x1F44A)),
                new MyEmojicon(getEmojiByUnicode(0x1F44B)),
                new MyEmojicon(getEmojiByUnicode(0x1F44C)),
                new MyEmojicon(getEmojiByUnicode(0x1F44D)),
                new MyEmojicon(getEmojiByUnicode(0x1F44E)),
                new MyEmojicon(getEmojiByUnicode(0x1F44F)),

                new MyEmojicon(getEmojiByUnicode(0x1F450)),
                new MyEmojicon(getEmojiByUnicode(0x1F451)),
                new MyEmojicon(getEmojiByUnicode(0x1F452)),
                new MyEmojicon(getEmojiByUnicode(0x1F453)),
                new MyEmojicon(getEmojiByUnicode(0x1F454)),
                new MyEmojicon(getEmojiByUnicode(0x1F455)),
                new MyEmojicon(getEmojiByUnicode(0x1F456)),
                new MyEmojicon(getEmojiByUnicode(0x1F457)),
                new MyEmojicon(getEmojiByUnicode(0x1F458)),
                new MyEmojicon(getEmojiByUnicode(0x1F459)),
                new MyEmojicon(getEmojiByUnicode(0x1F45A)),
                new MyEmojicon(getEmojiByUnicode(0x1F45B)),
                new MyEmojicon(getEmojiByUnicode(0x1F45C)),
                new MyEmojicon(getEmojiByUnicode(0x1F45D)),
                new MyEmojicon(getEmojiByUnicode(0x1F45E)),
                new MyEmojicon(getEmojiByUnicode(0x1F45F)),
                new MyEmojicon(getEmojiByUnicode(0x1F460)),
                new MyEmojicon(getEmojiByUnicode(0x1F461)),
                new MyEmojicon(getEmojiByUnicode(0x1F462)),
                new MyEmojicon(getEmojiByUnicode(0x1F463)),
                new MyEmojicon(getEmojiByUnicode(0x1F464)),
                new MyEmojicon(getEmojiByUnicode(0x1F465)),
                new MyEmojicon(getEmojiByUnicode(0x1F466)),
                new MyEmojicon(getEmojiByUnicode(0x1F467)),
                new MyEmojicon(getEmojiByUnicode(0x1F468)),
                new MyEmojicon(getEmojiByUnicode(0x1F469)),
                new MyEmojicon(getEmojiByUnicode(0x1F46A)),
                new MyEmojicon(getEmojiByUnicode(0x1F46B)),
                new MyEmojicon(getEmojiByUnicode(0x1F46E)),
                new MyEmojicon(getEmojiByUnicode(0x1F46F)),
                new MyEmojicon(getEmojiByUnicode(0x1F470)),
                new MyEmojicon(getEmojiByUnicode(0x1F471)),
                new MyEmojicon(getEmojiByUnicode(0x1F472)),
                new MyEmojicon(getEmojiByUnicode(0x1F473)),
                new MyEmojicon(getEmojiByUnicode(0x1F474)),
                new MyEmojicon(getEmojiByUnicode(0x1F475)),
                new MyEmojicon(getEmojiByUnicode(0x1F476)),
                new MyEmojicon(getEmojiByUnicode(0x1F477)),
                new MyEmojicon(getEmojiByUnicode(0x1F478)),
                new MyEmojicon(getEmojiByUnicode(0x1F479)),
                new MyEmojicon(getEmojiByUnicode(0x1F47A)),
                new MyEmojicon(getEmojiByUnicode(0x1F47B)),
                new MyEmojicon(getEmojiByUnicode(0x1F47C)),
                new MyEmojicon(getEmojiByUnicode(0x1F47D)),
                new MyEmojicon(getEmojiByUnicode(0x1F47E)),
                new MyEmojicon(getEmojiByUnicode(0x1F47F)),

                new MyEmojicon(getEmojiByUnicode(0x1F480)),
                new MyEmojicon(getEmojiByUnicode(0x1F481)),
                new MyEmojicon(getEmojiByUnicode(0x1F482)),
                new MyEmojicon(getEmojiByUnicode(0x1F483)),
                new MyEmojicon(getEmojiByUnicode(0x1F484)),
                new MyEmojicon(getEmojiByUnicode(0x1F485)),
                new MyEmojicon(getEmojiByUnicode(0x1F486)),
                new MyEmojicon(getEmojiByUnicode(0x1F487)),
                new MyEmojicon(getEmojiByUnicode(0x1F488)),
                new MyEmojicon(getEmojiByUnicode(0x1F489)),
                new MyEmojicon(getEmojiByUnicode(0x1F48A)),
                new MyEmojicon(getEmojiByUnicode(0x1F48B)),
                new MyEmojicon(getEmojiByUnicode(0x1F48C)),
                new MyEmojicon(getEmojiByUnicode(0x1F48D)),
                new MyEmojicon(getEmojiByUnicode(0x1F48E)),
                new MyEmojicon(getEmojiByUnicode(0x1F48F)),

                new MyEmojicon(getEmojiByUnicode(0x1F490)),
                new MyEmojicon(getEmojiByUnicode(0x1F491)),
                new MyEmojicon(getEmojiByUnicode(0x1F492)),
                new MyEmojicon(getEmojiByUnicode(0x1F493)),
                new MyEmojicon(getEmojiByUnicode(0x1F494)),
                new MyEmojicon(getEmojiByUnicode(0x1F495)),
                new MyEmojicon(getEmojiByUnicode(0x1F496)),
                new MyEmojicon(getEmojiByUnicode(0x1F497)),
                new MyEmojicon(getEmojiByUnicode(0x1F498)),
                new MyEmojicon(getEmojiByUnicode(0x1F499)),
                new MyEmojicon(getEmojiByUnicode(0x1F49A)),
                new MyEmojicon(getEmojiByUnicode(0x1F49B)),
                new MyEmojicon(getEmojiByUnicode(0x1F49C)),
                new MyEmojicon(getEmojiByUnicode(0x1F49D)),
                new MyEmojicon(getEmojiByUnicode(0x1F49E)),
                new MyEmojicon(getEmojiByUnicode(0x1F49F)),

                new MyEmojicon(getEmojiByUnicode(0x1F4A5)),
                new MyEmojicon(getEmojiByUnicode(0x1F4A6)),
                new MyEmojicon(getEmojiByUnicode(0x1F4A8)),
                new MyEmojicon(getEmojiByUnicode(0x1F4A9)),
                new MyEmojicon(getEmojiByUnicode(0x1F4AA)),
                new MyEmojicon(getEmojiByUnicode(0x1F4AB)),
                new MyEmojicon(getEmojiByUnicode(0x1F4AC)),
                new MyEmojicon(getEmojiByUnicode(0x1F600)),
                new MyEmojicon(getEmojiByUnicode(0x1F607)),
                new MyEmojicon(getEmojiByUnicode(0x1F608)),
                new MyEmojicon(getEmojiByUnicode(0x1F60E)),
                new MyEmojicon(getEmojiByUnicode(0x1F610)),
                new MyEmojicon(getEmojiByUnicode(0x1F611)),
                new MyEmojicon(getEmojiByUnicode(0x1F615)),
                new MyEmojicon(getEmojiByUnicode(0x1F617)),
                new MyEmojicon(getEmojiByUnicode(0x1F619)),
                new MyEmojicon(getEmojiByUnicode(0x1F61B)),
                new MyEmojicon(getEmojiByUnicode(0x1F61F)),
                new MyEmojicon(getEmojiByUnicode(0x1F626)),
                new MyEmojicon(getEmojiByUnicode(0x1F627)),
                new MyEmojicon(getEmojiByUnicode(0x1F62C)),
                new MyEmojicon(getEmojiByUnicode(0x1F62E)),
                new MyEmojicon(getEmojiByUnicode(0x1F62F)),
                new MyEmojicon(getEmojiByUnicode(0x1F634)),
                new MyEmojicon(getEmojiByUnicode(0x1F636)),
                new MyEmojicon(getEmojiByUnicode(0x1F46C)),
                new MyEmojicon(getEmojiByUnicode(0x1F46D)),

        };
        return DATA;
    }


    public static String getEmojiByUnicode(int unicode){
        return new String(Character.toChars(unicode));
    }

}